<?php
include_once './_common.php'; nl_require_approved();
$postTable=nl_table('anonymous_post');$commentTable=nl_table('anonymous_comment');$revealed=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
 nl_verify_csrf();$action=nl_post_str('action');
 if($action==='create_post'){
  $title=substr(nl_post_str('title'),0,255);$content=trim(nl_post_str('content'));if(!$title||!$content)alert('제목과 내용을 입력해 주세요.');if(mb_strlen($content)>10000)alert('내용은 10,000자 이하로 작성해 주세요.');
  $mb=nl_sql_escape($member['mb_id']);$t=nl_sql_escape($title);$c=nl_sql_escape($content);$now=nl_now();sql_query("INSERT INTO {$postTable} (author_mb_id,title,content,status,created_at,updated_at) VALUES ('{$mb}','{$t}','{$c}','active','{$now}','{$now}')",false);$r=sql_fetch("SELECT LAST_INSERT_ID() id",false);nl_audit('anonymous_post_create','anonymous_post',(int)($r['id']??0));goto_url(nl_url('anonymous.php'));
 }
 if($action==='comment'){
  $postId=(int)nl_post_str('post_id','0');$content=trim(nl_post_str('content'));if(!$postId||!$content)alert('댓글 내용을 입력해 주세요.');if(mb_strlen($content)>2000)alert('댓글은 2,000자 이하로 작성해 주세요.');
  $post=sql_fetch("SELECT id FROM {$postTable} WHERE id={$postId} AND status='active'",false);if(!$post)alert('댓글을 작성할 게시글을 찾을 수 없습니다.');$mb=nl_sql_escape($member['mb_id']);$c=nl_sql_escape($content);$now=nl_now();sql_query("INSERT INTO {$commentTable} (post_id,author_mb_id,content,status,created_at,updated_at) VALUES ({$postId},'{$mb}','{$c}','active','{$now}','{$now}')",false);nl_audit('anonymous_comment_create','anonymous_post',$postId);goto_url(nl_url('anonymous.php?view='.$postId));
 }
 if($action==='moderate'){
  if(!nl_can('board_moderate'))alert('익명 소통방 관리 권한이 없습니다.');$kind=nl_post_str('kind');$id=(int)nl_post_str('id','0');$status=nl_post_str('status')==='active'?'active':'hidden';$table=$kind==='comment'?$commentTable:$postTable;sql_query("UPDATE {$table} SET status='".nl_sql_escape($status)."',updated_at='".nl_now()."' WHERE id={$id}",false);nl_audit('anonymous_moderate',$kind==='comment'?'anonymous_comment':'anonymous_post',$id,array('status'=>$status));goto_url(nl_url('anonymous.php'.($kind==='comment'?'?view='.(int)nl_post_str('post_id','0'):'')));
 }
 if($action==='reveal'){
  if(!nl_can('anonymous_identity_reveal'))alert('익명 작성자 확인 권한이 없습니다.');$kind=nl_post_str('kind');$id=(int)nl_post_str('id','0');$table=$kind==='comment'?$commentTable:$postTable;$row=sql_fetch("SELECT author_mb_id FROM {$table} WHERE id={$id} LIMIT 1",false);if(!$row)alert('대상을 찾을 수 없습니다.');$who=get_member($row['author_mb_id']);$p=nl_profile($row['author_mb_id']);$revealed=array('kind'=>$kind,'id'=>$id,'mb_id'=>$row['author_mb_id'],'name'=>$who['mb_name']?:$who['mb_nick'],'role'=>$p['role_code']??'leader','department'=>$p['department']??'policy_office');nl_audit('anonymous_identity_reveal',$kind==='comment'?'anonymous_comment':'anonymous_post',$id,array('revealed_mb_id'=>$row['author_mb_id']));
 }
}
$viewId=(int)nl_get_str('view','0');$viewPost=array();$comments=array();
if($viewId){$viewPost=sql_fetch("SELECT * FROM {$postTable} WHERE id={$viewId} AND (status='active'".(nl_can('board_moderate')?" OR status='hidden'":"").") LIMIT 1",false);if(!$viewPost)alert('게시글을 찾을 수 없습니다.',nl_url('anonymous.php'));$res=sql_query("SELECT * FROM {$commentTable} WHERE post_id={$viewId} ".(nl_can('board_moderate')?"":"AND status='active' ")."ORDER BY id ASC",false);if($res)while($r=sql_fetch_array($res))$comments[]=$r;}
$res=sql_query("SELECT p.*,(SELECT COUNT(*) FROM {$commentTable} c WHERE c.post_id=p.id AND c.status='active') comment_count FROM {$postTable} p ".(nl_can('board_moderate')?"":"WHERE p.status='active' ")."ORDER BY p.id DESC LIMIT 80",false);$posts=array();if($res)while($r=sql_fetch_array($res))$posts[]=$r;
nl_enqueue_assets();$g5['title']='익명 소통방';include_once G5_PATH.'/head.php';
?>
<div class="nl-page nl-narrow"><div class="nl-page-head"><p class="nl-kicker">리더 소통</p><h1>익명 소통방</h1><p>일반 리더 화면에는 작성자 계정이 표시되지 않습니다. 작성자 확인은 별도 권한이 있는 경우에만 가능하며 확인 행위가 감사 로그에 기록됩니다.</p></div>
<?php if($revealed){ ?><div class="nl-alert nl-alert--warning"><strong>작성자 확인 결과</strong><br><?php echo nl_h($revealed['name']); ?> · <?php echo nl_h(nl_department_label($revealed['department'])); ?> · <?php echo nl_h(nl_role_label($revealed['role'])); ?> <span class="nl-note">(계정: <?php echo nl_h($revealed['mb_id']); ?>)</span></div><?php } ?>
<?php if($viewPost){ ?><article class="nl-panel"><div class="nl-anon-post__meta"><span>익명 리더</span><span><?php echo nl_h($viewPost['created_at']); ?></span><?php if($viewPost['status']!=='active')echo nl_status_badge($viewPost['status']);?></div><h2><?php echo nl_h($viewPost['title']); ?></h2><p class="nl-prose-pre"><?php echo nl_h($viewPost['content']); ?></p><div class="nl-actions nl-actions--top"><a class="nl-btn nl-btn--small" href="<?php echo nl_url('anonymous.php'); ?>">목록</a><?php if(nl_can('board_moderate')){ ?><form method="post"><?php echo nl_csrf_field(); ?><input type="hidden" name="action" value="moderate"><input type="hidden" name="kind" value="post"><input type="hidden" name="id" value="<?php echo (int)$viewPost['id']; ?>"><input type="hidden" name="status" value="<?php echo $viewPost['status']==='active'?'hidden':'active'; ?>"><button class="nl-btn nl-btn--small nl-btn--danger" type="submit"><?php echo $viewPost['status']==='active'?'숨김':'복원'; ?></button></form><?php } ?><?php if(nl_can('anonymous_identity_reveal')){ ?><form method="post"><?php echo nl_csrf_field(); ?><input type="hidden" name="action" value="reveal"><input type="hidden" name="kind" value="post"><input type="hidden" name="id" value="<?php echo (int)$viewPost['id']; ?>"><button class="nl-btn nl-btn--small" data-confirm="익명 작성자 확인은 감사 로그에 기록됩니다. 계속할까요?" type="submit">작성자 확인</button></form><?php } ?></div>
<ul class="nl-comments"><?php foreach($comments as $c){ ?><li><small>익명 리더 · <?php echo nl_h($c['created_at']); ?> <?php if($c['status']!=='active')echo '· 숨김'; ?></small><div><?php echo nl_h($c['content']); ?></div><?php if(nl_can('board_moderate')||nl_can('anonymous_identity_reveal')){ ?><div class="nl-actions nl-actions--compact"><?php if(nl_can('board_moderate')){ ?><form method="post"><?php echo nl_csrf_field(); ?><input type="hidden" name="action" value="moderate"><input type="hidden" name="kind" value="comment"><input type="hidden" name="post_id" value="<?php echo (int)$viewPost['id']; ?>"><input type="hidden" name="id" value="<?php echo (int)$c['id']; ?>"><input type="hidden" name="status" value="<?php echo $c['status']==='active'?'hidden':'active'; ?>"><button class="nl-btn nl-btn--small" type="submit"><?php echo $c['status']==='active'?'숨김':'복원'; ?></button></form><?php } ?><?php if(nl_can('anonymous_identity_reveal')){ ?><form method="post"><?php echo nl_csrf_field(); ?><input type="hidden" name="action" value="reveal"><input type="hidden" name="kind" value="comment"><input type="hidden" name="id" value="<?php echo (int)$c['id']; ?>"><button class="nl-btn nl-btn--small" data-confirm="작성자 확인 기록이 남습니다. 계속할까요?" type="submit">작성자 확인</button></form><?php } ?></div><?php } ?></li><?php } ?></ul><form method="post" class="nl-form nl-form--nested"><?php echo nl_csrf_field(); ?><input type="hidden" name="action" value="comment"><input type="hidden" name="post_id" value="<?php echo (int)$viewPost['id']; ?>"><div class="nl-field"><label>익명 댓글</label><textarea name="content" maxlength="2000" required></textarea></div><button class="nl-btn nl-btn--primary" type="submit">댓글 등록</button></form></article><?php } else { ?>
<details class="nl-panel nl-panel--spaced"><summary><strong>새 글 작성</strong></summary><form method="post" class="nl-form nl-form--nested"><?php echo nl_csrf_field(); ?><input type="hidden" name="action" value="create_post"><div class="nl-field"><label>제목</label><input name="title" type="text" maxlength="255" required></div><div class="nl-field"><label>내용</label><textarea name="content" maxlength="10000" required></textarea></div><button class="nl-btn nl-btn--primary" type="submit">익명으로 등록</button></form></details>
<div><?php if(!$posts)echo '<div class="nl-empty">아직 작성된 글이 없습니다.</div>';foreach($posts as $p){ ?><article class="nl-anon-post"><a href="<?php echo nl_url('anonymous.php?view='.(int)$p['id']); ?>"><div class="nl-anon-post__meta"><span>익명 리더</span><span><?php echo nl_h($p['created_at']); ?></span><?php if($p['status']!=='active')echo nl_status_badge($p['status']);?></div><h3><?php echo nl_h($p['title']); ?></h3><p><?php echo nl_h(mb_strimwidth($p['content'],0,180,'…','UTF-8')); ?></p><small>댓글 <?php echo (int)$p['comment_count']; ?></small></a></article><?php } ?></div><?php } ?></div>
<?php include_once G5_PATH.'/tail.php'; ?>
